/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ida Faber (https://sketchfab.com/Ida..Faber)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiba-inu-dog-80419f7e64e24afe97e0931b6aeee612
Title: Shiba Inu Dog
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import scene from '../assets/3d/shiba_inu_dog.glb'

const Dog = ({currentAnimation, ...props}) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  useEffect(()=> {

  }, [actions, currentAnimation])
  return (
    <group {...props} ref={group} dispose={null}>
      <group position={[0, 4.05, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface2_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface3_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface4_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface5_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface6_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface7_lambert1_0.geometry}
          material={materials.lambert1}
        />
      </group>
    </group>
  )
}

//useGLTF.preload('/shiba_inu_dog.glb')

export default Dog;
//credit: "Shiba Inu Dog" (https://skfb.ly/6QYIW) by Ida Faber is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/).